apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    ingress:
      enabled: false
    auth:
      enabled: true
      appClientId: registry-client-api
      uiClientId: registry-client-ui
      authServerUrl: https://$KEYCLOAK_INGRESS_URL/realms/registry
      redirectUri: https://$UI_INGRESS_URL
      logoutUrl: https://$UI_INGRESS_URL
      basicAuth:
        enabled: true
        cacheExpiration: 25m
      tls:
        tlsVerificationType: none
      authz:
        enabled: true
        ownerOnlyEnabled: true
        adminOverride:
          enabled: true
    features:
      resourceDeleteEnabled: true
  ui:
    ingress:
      enabled: false
    env:
      - name: REGISTRY_API_URL
        value: https://$APP_INGRESS_URL/apis/registry/v3
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-registry-app
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: $APPLICATION_NAME
spec:
  host: $APP_INGRESS_URL
  to:
    kind: Service
    name: registry-app-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurio-registry-ui
  annotations:
    kubernetes.io/tls-acme: "true"
  labels:
    app: $APPLICATION_NAME
spec:
  host: $UI_INGRESS_URL
  to:
    kind: Service
    name: registry-ui-service
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
