apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    ingress:
      host: $APP_INGRESS_URL
    features:
      resourceDeleteEnabled: true
    env:
      - name: APICURIO_STORAGE_SQL_KIND
        value: "mysql"
      - name: APICURIO_DATASOURCE_URL
        value: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      - name: APICURIO_DATASOURCE_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: APICURIO_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
  ui:
    ingress:
      host: $UI_INGRESS_URL
