apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    ingress:
      host: $APP_INGRESS_URL
    features:
      resourceDeleteEnabled: true
    env:
      - name: APICURIO_FEATURES_EXPERIMENTAL_ENABLED
        value: "true"
      - name: APICURIO_SEARCH_INDEX_ENABLED
        value: "true"
      - name: QUARKUS_ELASTICSEARCH_HOSTS
        value: "elasticsearch-es-http:9200"
      - name: QUARKUS_ELASTICSEARCH_USERNAME
        value: "elastic"
      - name: QUARKUS_ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-es-elastic-user
            key: elastic
  ui:
    ingress:
      host: $UI_INGRESS_URL
