apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: $APPLICATION_NAME
spec:
  app:
    storage:
      type: postgresql
      sql:
        dataSource:
          url: jdbc:postgresql://postgresql:5432/${POSTGRESQL_DATABASE}
          username:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_USER
          password:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
    ingress:
      host: $APP_INGRESS_URL
    features:
      resourceDeleteEnabled: true
  ui:
    ingress:
      host: $UI_INGRESS_URL
