apiVersion: v1
kind: Pod
metadata:
  name: certbot-pod
  namespace: $NAMESPACE
spec:
  restartPolicy: Never
  containers:
  - name: certbot
    image: certbot/dns-route53:latest
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]  # Keep container running
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_DEFAULT_REGION
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_DEFAULT_REGION
    volumeMounts:
    - name: letsencrypt
      mountPath: /etc/letsencrypt
    - name: letsencrypt-work
      mountPath: /var/lib/letsencrypt
    - name: letsencrypt-logs
      mountPath: /var/log/letsencrypt
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
  volumes:
  - name: letsencrypt
    emptyDir: {}
  - name: letsencrypt-work
    emptyDir: {}
  - name: letsencrypt-logs
    emptyDir: {}
